### ISSUE TITLE
License file?

### ISSUE THREAD

**Issue by forestbeasts** [wiiu-env/EnvironmentLoader#10]
The other Tiramisu repos have licenses on them, but this one doesn't seem to.

Some of the files here have GPL3 headers in them, but others don't... could you maybe add a license to clarify, if you're cool with it being open source? (Without a license nobody's allowed to do things like keep maintaining it if you stop working on it.) It miiiight already count as GPL3 since nothing contradicts those files that do have licenses, but clarification never hurts.

Thanks!

**Comment by forestbeasts** [comment]
Oh huh, looks like most of the other Tiramisu repos don't have licenses either.

**Comment by Maschell** [comment]
Added with c976e0a78893106ac21f55567b93db021c2cbd67
