### ISSUE TITLE
Black screen on boot

### ISSUE THREAD

**Issue by yllekz** [wiiu-env/EnvironmentLoader#39]
I updated to the latest EnvironmentLoader but the Wii U now locks on a black screen after the Wii U logo. Did the latest update cause an issue?

**Comment by Maschell** [comment]
Delete the SNTP Client plugin if you have it on your sd card.
If this doesn't help try to redownload the environment loader and aroma to a fresh sd card

**Comment by yllekz** [comment]
I eventually took care of it by reinstalling a significant portion of the homebrew files per wiiu.hacks.guide, which also involved replacing the environmentloader files with different ones the site linked as opposed to the ones on the releases page which appeared to fix it. Seems to be a weird versioning issue.
